# Generated by Django 5.2.12 on 2026-03-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('stock_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='portfolio.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='stock_master.stockmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'portfolio', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='UserStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField()),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('user_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='user_stock.userstock')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('user_stock', 'timestamp')},
            },
        ),
    ]
