# Generated by Django 5.2.12 on 2026-03-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0002_newsarticle_ticker_link_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsarticle',
            new_name='advanced_ne_ticker_5876ed_idx',
            old_name='advanced_ne_ticker__3f4489_idx',
        ),
    ]
