# Generated by Django 5.2.12 on 2026-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stock_master',
                'ordering': ['stock_name', 'ticker'],
            },
        ),
    ]
