# Generated by Django 5.2.12 on 2026-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_master', '0002_stockmaster_yahoo_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category_type', models.CharField(choices=[('INDEX', 'Index'), ('SECTOR', 'Sector'), ('INTERNATIONAL', 'International'), ('THEME', 'Theme')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='stock_master.stockcategory'),
        ),
    ]
